version: '2.2'
services:
    tabby:
        build: .
        ports:
            - 80
        environment:
            TABBY_DOMAIN: localhost
            TABBY_DB_USER: tabby
            TABBY_DB_PASSWORD: tabby
            TABBY_SMTP_SERVER: mailcatcher:1025
        depends_on:
            - mailcatcher
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080


